#!/usr/bin/env python3
"""Build an explainer episode: script -> timeline -> Remotion render -> mastered MP4.

  python make.py survivorship                 # full render -> out/survivorship.mp4
  python make.py survivorship --plan          # timeline + fonts only, print the schedule
  python make.py survivorship --stills        # QA contact sheet (one frame per subtitle)
  python make.py survivorship --stills 12.5 40 # specific times (seconds)
  python make.py survivorship --preview 45 70 # render a time range, with music
  python make.py survivorship --share         # small copy of out/<id>.mp4 for chat/preview (~2.5 Mbps)
  npm run studio                              # live preview (run --plan first)
"""

import argparse
import glob
import json
import os
import shutil
import subprocess
import sys
import time

import yaml

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)
from pipeline import fonts, music, timeline  # noqa: E402

BROWSER = os.environ.get("REMOTION_BROWSER") or next(
    iter(glob.glob("/opt/pw-browsers/chromium_headless_shell-*/chrome-linux/headless_shell")), None)


def run(cmd, **kw):
    print("$", " ".join(cmd if len(" ".join(cmd)) < 300 else cmd[:6] + ["..."]), flush=True)
    subprocess.run(cmd, check=True, **kw)


def write_registry():
    """src/registry.generated.ts: every episode that ships its own scenes.tsx."""
    lines = ["// Generated by make.py. Do not edit.", "import type {SceneMap} from './lib/types';"]
    entries = []
    for i, path in enumerate(sorted(glob.glob(os.path.join(ROOT, "episodes", "*", "scenes.tsx")))):
        ep = os.path.basename(os.path.dirname(path))
        lines.append(f"import {{scenes as e{i}}} from '../episodes/{ep}/scenes';")
        entries.append(f"  {json.dumps(ep)}: e{i},")
    lines += ["", "export const registry: Record<string, SceneMap> = {", *entries, "};", ""]
    text = "\n".join(lines)
    path = os.path.join(ROOT, "src", "registry.generated.ts")
    if not os.path.exists(path) or open(path).read() != text:
        with open(path, "w") as f:
            f.write(text)


def snap_cuts(cuts, beats, phrase=16, anchor=None):
    """Snap each [from, to] (seconds, original track) to the beat grid: both ends on a phrase line
    (every `phrase` beats, counted from `anchor`, a beat index on a phrase start) and a whole number of
    phrases long. Cutting part of a phrase leaves an odd-length phrase and the ear hears the jump."""
    period = (beats[-1] - beats[0]) / (len(beats) - 1)
    anchor = anchor or 0
    out = []
    for a, b in cuts:
        ia = min(range(len(beats)), key=lambda i: abs(beats[i] - a))
        ia = anchor + round((ia - anchor) / phrase) * phrase
        n = max(phrase, round((b - a) / period / phrase) * phrase)
        ib = min(ia + n, len(beats) - 1)
        out.append((beats[ia] - 0.02, beats[ib] - 0.02))
    return sorted(out)


def through_cuts(t, cuts):
    """Original track time -> edited track time (a time inside a cut maps to the cut point)."""
    d = 0.0
    for a, b in cuts:
        if t >= b:
            d += b - a
        elif t > a:
            return a - d
    return t - d


def edit_music(info, cuts):
    """The analysis of the edited track, derived from the original's (no re-analysis, so beats stay put)."""
    inside = lambda t: any(a < t < b for a, b in cuts)
    e = dict(info)
    e["beats"] = [through_cuts(t, cuts) for t in info["beats"] if not inside(t)]
    e["hits"] = [[through_cuts(t, cuts), s] for t, s in info["hits"] if not inside(t)]
    e["markers"] = {k: through_cuts(v, cuts) for k, v in info["markers"].items()}
    hz = info["energy_hz"]
    e["energy"] = [v for i, v in enumerate(info["energy"]) if not inside(i / hz)]
    e["duration"] = info["duration"] - sum(b - a for a, b in cuts)
    return e


def cut_track(src, cuts, dst):
    """Remove whole bars from the track, joined with short crossfades on the beat."""
    total = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", src],
                                 capture_output=True, text=True).stdout.strip())
    keep, t = [], 0.0
    for a, b in cuts:
        keep.append((t, a))
        t = b
    keep.append((t, total))
    # each later piece starts one crossfade early: acrossfade overlaps the pieces by `X`, and without
    # this every cut would pull the rest of the track 30 ms early (v2 drifted ~90 ms by the drop)
    X = 0.03
    parts = [f"[0:a]atrim={max(0.0, a - (X if i else 0))}:{b},asetpts=PTS-STARTPTS[s{i}]" for i, (a, b) in enumerate(keep)]
    chain, last = [], "s0"
    for i in range(1, len(keep)):
        chain.append(f"[{last}][s{i}]acrossfade=d={X}:c1=tri:c2=tri[x{i}]")
        last = f"x{i}"
    run(["ffmpeg", "-v", "error", "-y", "-i", src, "-filter_complex", ";".join(parts + chain), "-map", f"[{last}]",
         "-ar", "48000", "-c:a", "pcm_s16le", dst])


def plan(ep_id):
    ep_dir = os.path.join(ROOT, "episodes", ep_id)
    with open(os.path.join(ep_dir, "episode.yaml"), encoding="utf-8") as f:
        ep = yaml.safe_load(f)
    out = os.path.join(ROOT, "public", "build", ep_id)
    os.makedirs(out, exist_ok=True)

    track = os.path.join(ROOT, ep["music"])
    cache = os.path.join(out, "music.json")
    if os.path.exists(cache) and json.load(open(cache)).get("mtime") == os.path.getmtime(track) and "hits" in json.load(open(cache)):
        info = json.load(open(cache))
    else:
        print("analysing music...")
        info = music.analyse(track)
        info["mtime"] = os.path.getmtime(track)
        json.dump(info, open(cache, "w"))
    if ep.get("music_cut"):
        # pacing: whole bars cut out of the track (markers in episode.yaml stay in original-track time)
        # the phrase grid: the break starts a phrase (music.py's section markers sit on phrase lines)
        brk = info["markers"].get("break", 0)
        anchor = min(range(len(info["beats"])), key=lambda i: abs(info["beats"][i] - brk))
        cuts = snap_cuts(ep["music_cut"], info["beats"], 16, anchor)
        edited = os.path.join(out, "bgm.edit.wav")
        key = json.dumps([os.path.getmtime(track), cuts])
        if not (os.path.exists(edited) and os.path.exists(edited + ".key") and open(edited + ".key").read() == key):
            cut_track(track, cuts, edited)
            open(edited + ".key", "w").write(key)
        info = edit_music(info, cuts)
        ep = {**ep, "markers": {k: through_cuts(v, cuts) for k, v in ep.get("markers", {}).items()}, "_track": edited}
        print("music cut (original s → removed):", [(round(a, 2), round(b - a, 2)) for a, b in cuts],
              f"→ {info['duration']:.1f}s")
        track = edited
    shutil.copyfile(track, os.path.join(out, "bgm" + os.path.splitext(track)[1]))

    tl = timeline.build(ep, info)
    tl["music"]["src"] = f"build/{ep_id}/bgm{os.path.splitext(track)[1]}"
    json.dump(tl, open(os.path.join(out, "timeline.json"), "w"), ensure_ascii=False)
    n = fonts.build(ep_dir, os.path.join(out, "fonts"))
    write_registry()

    fps = tl["fps"]
    print(f"\n{tl['title']}  {tl['width']}x{tl['height']}@{fps}  {tl['durationInFrames'] / fps:.1f}s  "
          f"tempo {info['tempo']} bpm  {n} glyphs")
    print("markers:", {k: round(v / fps, 2) for k, v in tl["music"]["markers"].items()})
    for s in tl["scenes"]:
        print(f"  {s['from'] / fps:6.2f}s  {s['duration'] / fps:5.1f}s  {s['id']:<10} {s['component']}")
        for ln in s["lines"]:
            if ln["text"]:
                print(f"      {(s['from'] + ln['from']) / fps:6.2f}  {ln['duration'] / fps:4.1f}s  {ln['text']}")
    return ep, tl


def remotion(args_):
    if not BROWSER:
        sys.exit("No Chromium found; set REMOTION_BROWSER to a chrome-headless-shell binary.")
    run(["npx", "remotion", *args_, f"--browser-executable={BROWSER}"], cwd=ROOT)


def render_video(ep_id, path, frames=None, concurrency=None):
    cmd = ["render", "src/index.ts", "Episode", path, f"--props={json.dumps({'episode': ep_id})}",
           "--muted", "--codec=h264", "--crf=18", "--x264-preset=slow", "--image-format=jpeg", "--jpeg-quality=94",
           "--pixel-format=yuv420p", "--log=error", "--timeout=300000"]
    if frames:
        cmd.append(f"--frames={frames[0]}-{frames[1]}")
    if concurrency:
        cmd.append(f"--concurrency={concurrency}")
    remotion(cmd)


def master_audio(tl, track, start, dur, path):
    """Cut the BGM to the picture, fade the tail, normalise to -14 LUFS (two-pass loudnorm)."""
    fade = min(2.5, dur / 4)
    chain = f"atrim={start}:{start + dur},asetpts=PTS-STARTPTS,afade=t=in:d=0.05,afade=t=out:st={dur - fade}:d={fade}"
    probe = subprocess.run(["ffmpeg", "-hide_banner", "-i", track, "-af",
                            chain + ",loudnorm=I=-14:TP=-1.5:LRA=11:print_format=json", "-f", "null", "-"],
                           capture_output=True, text=True).stderr
    m = json.loads(probe[probe.rindex("{"):probe.rindex("}") + 1])
    ln = (f"loudnorm=I=-14:TP=-1.5:LRA=11:measured_I={m['input_i']}:measured_TP={m['input_tp']}:"
          f"measured_LRA={m['input_lra']}:measured_thresh={m['input_thresh']}:offset={m['target_offset']}:linear=true")
    run(["ffmpeg", "-v", "error", "-y", "-i", track, "-af", f"{chain},{ln}", "-ar", "48000", "-c:a", "pcm_s16le", path])


def mux(video, audio, out):
    run(["ffmpeg", "-v", "error", "-y", "-i", video, "-i", audio, "-map", "0:v", "-map", "1:a",
         "-c:v", "copy", "-c:a", "aac", "-b:a", "256k", "-movflags", "+faststart", "-shortest", out])


def share_copy(src, dst, kbps=2500):
    """Two-pass x264 at a fixed bitrate: a light file for sending around (the master stays CRF 18)."""
    log = os.path.join(os.path.dirname(dst), "x264pass")
    base = ["ffmpeg", "-v", "error", "-y", "-i", src, "-c:v", "libx264", "-preset", "slow", "-b:v", f"{kbps}k",
            "-pix_fmt", "yuv420p", "-passlogfile", log]
    run(base + ["-pass", "1", "-an", "-f", "mp4", os.devnull])
    run(base + ["-pass", "2", "-c:a", "aac", "-b:a", "160k", "-movflags", "+faststart", dst])
    for f in glob.glob(log + "*"):
        os.remove(f)


def stills(ep_id, tl, times):
    fps = tl["fps"]
    if not times:
        times = [(s["from"] + 0.8 * (s["to"] - s["from"])) / fps for s in tl["subtitles"]]
    d = os.path.join(ROOT, "out", f"{ep_id}-stills")
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)
    run(["node", "scripts/stills.mjs", ep_id, d, *[str(int(t * fps)) for t in times]], cwd=ROOT,
        env={**os.environ, "REMOTION_BROWSER": BROWSER or ""})
    sheet = os.path.join(ROOT, "out", f"{ep_id}-contact.jpg")
    cols = 6 if tl["format"] == "vertical" else 4
    run(["ffmpeg", "-v", "error", "-y", "-pattern_type", "glob", "-i", os.path.join(d, "*.jpg"), "-vf",
         f"scale=480:-1,tile={cols}x{(len(times) + cols - 1) // cols}:padding=6:color=0x222222",
         "-frames:v", "1", "-update", "1", sheet])
    print("wrote", sheet)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("episode")
    ap.add_argument("--plan", action="store_true")
    ap.add_argument("--stills", nargs="*", type=float)
    ap.add_argument("--preview", nargs=2, type=float, metavar=("START", "END"))
    ap.add_argument("--share", action="store_true", help="only re-encode out/<id>.mp4 into out/<id>-share.mp4")
    ap.add_argument("--concurrency", type=int)
    a = ap.parse_args()
    t0 = time.time()
    ep, tl = plan(a.episode)
    if a.plan:
        return
    if a.share:
        src = os.path.join(ROOT, "out", f"{a.episode}.mp4")
        share_copy(src, os.path.join(ROOT, "out", f"{a.episode}-share.mp4"))
        return
    if a.stills is not None:
        stills(a.episode, tl, a.stills)
        return
    out = os.path.join(ROOT, "out")
    os.makedirs(out, exist_ok=True)
    tmp = os.path.join(ROOT, "public", "build", a.episode)
    track = ep.get("_track") or os.path.join(ROOT, ep["music"])
    fps = tl["fps"]
    if a.preview:
        f0, f1 = int(a.preview[0] * fps), min(int(a.preview[1] * fps), tl["durationInFrames"]) - 1
        name = f"{a.episode}-preview-{a.preview[0]:g}-{a.preview[1]:g}"
    else:
        f0, f1, name = 0, tl["durationInFrames"] - 1, a.episode
    video = os.path.join(tmp, f"{name}.video.mp4")
    render_video(a.episode, video, (f0, f1) if a.preview else None, a.concurrency)
    audio = os.path.join(tmp, f"{name}.audio.wav")
    master_audio(tl, track, f0 / fps, (f1 - f0 + 1) / fps, audio)
    final = os.path.join(out, f"{name}.mp4")
    mux(video, audio, final)
    print(f"wrote {final} in {time.time() - t0:.0f}s")


if __name__ == "__main__":
    main()
